name: song4story
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pillow=10.4.0
  - faiss-cpu=1.8.0
  - scikit-learn=1.5.1
  - pip
  - pip:
      - streamlit==1.50.0
      - wordfreq==3.1.1
      - torch==2.4.1
      - torchvision==0.19.1
      - open-clip-torch==2.24.0
      - rapidfuzz==3.9.6




