name: song4story
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pillow=10.4.0
  - faiss-cpu=1.8.0
  - scikit-learn=1.6.1
  - pip
  # environment.yml (pip section)
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch==2.6.0+cpu
    - torchvision==0.21.0+cpu
    - streamlit==1.50.0
    - wordfreq==3.1.1
    - open-clip-torch==2.24.0
    - rapidfuzz==3.9.6
    - numpy<2
    - clip-interrogator==0.6.0
    - transformers>=4.43,<5
    - sentencepiece==0.2.1
    - timm==1.0.20




