name: song4story
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - numpy-base=1.26.4
  - mkl-service
  - mkl
  - faiss-cpu=1.7.4
  - torchvision=0.19.1
  - pytorch=2.4.1
  - cpuonly
  - pip:
      - wordfreq==3.1.1
    



